USE [master]
GO
CREATE LOGIN [PizzaPOSUser] WITH PASSWORD=N'Burnt3Pizzas!', DEFAULT_DATABASE=[PizzaPOS], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
CREATE USER [PizzaPOS] FOR LOGIN [PizzaPOSUser] WITH DEFAULT_SCHEMA=[dbo]
GO
